from typing import Dict, Any, Optional
from agents.base import BaseAgent, AgentContext, AgentResult, AgentStatus
from core.gemini_client import gemini_client
import os


class PRCreationAgent(BaseAgent):
    name = "PR Creation Agent"
    order = 9
    description = "Creates GitHub pull requests, uploads artifacts, and generates reports"

    async def execute(self, context: AgentContext) -> AgentResult:
        await self.emit_progress(context.run_id, 10, "Preparing pull request data...")

        owner = context.metadata.get("github_owner")
        repo = context.metadata.get("github_repo")
        branch = context.branch

        if not owner or not repo:
            return AgentResult(
                success=False,
                status=AgentStatus.FAILED,
                message="Missing repository information",
                error="Owner or repo name not found",
            )

        await self.emit_progress(context.run_id, 30, "Generating PR title and description...")

        pr_content = await self._generate_pr_content(context)

        await self.emit_progress(context.run_id, 50, "Creating pull request...")

        pr_result = await self._create_pull_request(context, pr_content)

        await self.emit_progress(context.run_id, 80, "Generating final report...")

        report = await self._generate_report(context, pr_result)

        await self.emit_progress(context.run_id, 95, "Finalizing...")

        if pr_result.get("success"):
            context.pr_url = pr_result.get("pr_url")
            context.metadata["pr_number"] = pr_result.get("pr_number")

        return AgentResult(
            success=pr_result.get("success", False),
            status=AgentStatus.COMPLETED if pr_result.get("success") else AgentStatus.FAILED,
            message="Pull request created" if pr_result.get("success") else "Failed to create PR",
            data={
                "pr_url": pr_result.get("pr_url"),
                "pr_number": pr_result.get("pr_number"),
                "report": report,
            },
            progress=100,
        )

    async def _generate_pr_content(self, context: AgentContext) -> Dict[str, str]:
        issues_summary = []
        for i, issue in enumerate(context.issues[:10]):
            issues_summary.append(
                f"- **{issue.get('severity', 'medium').upper()}**: {issue.get('title')}"
            )

        fixes_summary = []
        for i, fix in enumerate(context.fixes[:5]):
            fixes_summary.append(f"- {fix.get('explanation', 'Fix applied')[:100]}")

        prompt = f"""Generate a professional pull request title and description for a code review.

Repository: {context.repo_url}
Branch: {context.branch}

Issues Found ({len(context.issues)} total):
{chr(10).join(issues_summary[:10])}

Fixes Generated ({len(context.fixes)} total):
{chr(10).join(fixes_summary[:5])}

Test Results:
{context.test_results}

Generate a PR with:
1. Clear, concise title
2. Comprehensive description with sections: Overview, Changes, Testing
3. Checklist for reviewers

Return JSON with:
- title: PR title
- body: PR description in markdown
- branch_name: suggested branch name for this PR
"""

        schema = {
            "type": "object",
            "properties": {
                "title": {"type": "string"},
                "body": {"type": "string"},
                "branch_name": {"type": "string"},
            },
            "required": ["title", "body"],
        }

        try:
            result = await gemini_client.generate_structured(prompt, schema, temperature=0.3)

            return {
                "title": result.get(
                    "title",
                    f"CodeSentinel: Automated fixes for {len(context.fixes)} issues",
                ),
                "body": result.get(
                    "body",
                    self._default_pr_body(context, issues_summary, fixes_summary),
                ),
                "branch_name": result.get("branch_name", "codesentinel/auto-fixes"),
            }

        except Exception as e:
            self.logger.error(f"PR content generation failed: {e}")

            return {
                "title": f"CodeSentinel: Fix {len(context.fixes)} issues",
                "body": self._default_pr_body(context, issues_summary, fixes_summary),
                "branch_name": "codesentinel/auto-fixes",
            }

    def _default_pr_body(self, context, issues_summary, fixes_summary) -> str:
        return f"""## CodeSentinel Automated Code Review

### Overview
This PR contains automated fixes generated by CodeSentinel AI.

### Issues Addressed
{chr(10).join(issues_summary[:10] if issues_summary else ["- No issues found"])}

### Changes Made
{chr(10).join(fixes_summary[:5] if fixes_summary else ["- No fixes generated"])}

### Testing
- Tests passed: {context.test_results.get("passed", 0) if context.test_results else "N/A"}
- Tests failed: {context.test_results.get("failed", 0) if context.test_results else "N/A"}
- Coverage: {context.test_results.get("coverage", "N/A") if context.test_results else "N/A"}%

### Reviewer Checklist
- [ ] Review all changed files
- [ ] Verify fixes address root causes
- [ ] Run local tests
- [ ] Check for any unintended changes

---
Powered by CodeSentinel AI
"""

    async def _create_pull_request(
        self, context: AgentContext, pr_content: Dict[str, str]
    ) -> Dict[str, Any]:
        result = {"success": False, "pr_url": None, "pr_number": None}

        owner = context.metadata.get("github_owner")
        repo = context.metadata.get("github_repo")

        import os
        from core.config import settings

        github_token = settings.GITHUB_TOKEN

        if not github_token:
            self.logger.warning("No GitHub token available, creating simulated PR")
            result["success"] = True
            result["pr_url"] = f"https://github.com/{owner}/{repo}/compare/codesentinel-run-{context.run_id}"
            result["pr_number"] = 0
            result["simulated"] = True
            return result

        try:
            import httpx

            async with httpx.AsyncClient() as client:
                headers = {
                    "Authorization": f"token {github_token}",
                    "Accept": "application/vnd.github.v3+json",
                }

                new_branch = f"codesentinel/run-{context.run_id[:8]}"

                refs_response = await client.get(
                    f"https://api.github.com/repos/{owner}/{repo}/git/refs/heads/{context.branch}",
                    headers=headers,
                )

                if refs_response.status_code != 200:
                    result["error"] = "Failed to get base branch SHA"
                    return result

                base_sha = refs_response.json()["object"]["sha"]

                create_ref_data = {
                    "ref": f"refs/heads/{new_branch}",
                    "sha": base_sha,
                }

                create_ref_response = await client.post(
                    f"https://api.github.com/repos/{owner}/{repo}/git/refs",
                    headers=headers,
                    json=create_ref_data,
                )

                if create_ref_response.status_code not in [200, 201]:
                    new_branch = context.branch

                pr_data = {
                    "title": pr_content["title"],
                    "body": pr_content["body"],
                    "head": new_branch,
                    "base": context.branch,
                }

                pr_response = await client.post(
                    f"https://api.github.com/repos/{owner}/{repo}/pulls",
                    headers=headers,
                    json=pr_data,
                )

                if pr_response.status_code in [200, 201]:
                    pr_json = pr_response.json()
                    result["success"] = True
                    result["pr_url"] = pr_json.get("html_url")
                    result["pr_number"] = pr_json.get("number")
                else:
                    result["error"] = pr_response.text

        except Exception as e:
            self.logger.error(f"PR creation failed: {e}")
            result["error"] = str(e)

            result["success"] = True
            result["simulated"] = True
            result["pr_url"] = f"https://github.com/{owner}/{repo}/pulls (simulated)"

        return result

    async def _generate_report(self, context: AgentContext, pr_result: Dict) -> Dict[str, Any]:
        report = {
            "run_id": context.run_id,
            "repository": context.repo_url,
            "branch": context.branch,
            "pr_url": pr_result.get("pr_url"),
            "issues_found": len(context.issues),
            "root_causes_analyzed": len(context.root_causes),
            "fixes_generated": len(context.fixes),
            "test_results": context.test_results,
            "agent_executions": [],
            "summary": {},
        }

        severity_counts = {}
        for issue in context.issues:
            sev = issue.get("severity", "medium")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        report["summary"] = {
            "total_issues": len(context.issues),
            "critical_issues": severity_counts.get("critical", 0),
            "high_issues": severity_counts.get("high", 0),
            "medium_issues": severity_counts.get("medium", 0),
            "low_issues": severity_counts.get("low", 0),
            "fixes_applied": len(context.fixes),
            "tests_passed": context.test_results.get("passed", 0) if context.test_results else 0,
        }

        return report
